export const GET_INGREDIENTS_REQ = 'GET_INGREDIENTS_REQ';
export const GET_INGREDIENTS_SUCC = 'GET_INGREDIENTS_SUCC';
export const GET_INGREDIENTS_ERR = 'GET_INGREDIENTS_ERR';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const HIDE_DETAILS = 'HIDE_DETAILS';

export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ADD_BUN = 'ADD_BUN';
export const DELETE_BUN = 'DELETE_BUN';
export const CREATE_ORDER_OBJ = 'CREATE_ORDER_OBJ';
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
